@echo off
setlocal
set "MSI=%~dp0..\PcNinja-WinUpdateTool-V1.1.2-Setup-x64.msi"
msiexec /i "%MSI%" /qn /norestart ^
  PCNINJA_ENABLE_SCHEDULE=1 ^
  PCNINJA_FREQUENCY=Monthly ^
  PCNINJA_MONTHLY_DAY=15 ^
  PCNINJA_TIME=03:00 ^
  PCNINJA_RUN_AT_STARTUP=1 ^
  PCNINJA_STARTUP_DELAY=5 ^
  PCNINJA_RUN_IF_MISSED=1 ^
  PCNINJA_WAKE_TO_RUN=1 ^
  PCNINJA_ALLOW_FIRMWARE=0 ^
  PCNINJA_REBOOT_PROMPT=1 ^
  PCNINJA_ENABLE_AUTORETRY=1 ^
  PCNINJA_RETRY_INITIAL_DELAY=5 ^
  PCNINJA_RETRY_MAX_ATTEMPTS=3 ^
  PCNINJA_RETRY_BACKOFF=2 ^
  PCNINJA_MINIMUM_COOLDOWN=5
exit /b %ERRORLEVEL%

